---
- name: Set up a target with Docker
  hosts: myhosts
  gather_facts: true
  become: true
  vars:
    distro_name: "{{ ansible_distribution | lower }}"
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        update_cache: true
    - name: Add Docker’s official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/{{ distro_name }}/gpg
        state: present
    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/{{ distro_name }} {{ ansible_distribution_release }} stable
        state: present
    - name: Install Docker
      ansible.builtin.package:
        name: docker-ce
        update_cache: true
    - name: Install ncdu, vim, rsyslog, htop
      ansible.builtin.package:
        name:
          - ncdu
          - vim
          - rsyslog
          - htop
        update_cache: true
    - name: Add the user 'carebot', appending the group 'docker' to the user's groups
      ansible.builtin.user:
        name: carebot
        groups: docker
    - name: Copy daemon.json to set up log rotation policy
      ansible.builtin.copy:
        src: daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: "0644"
