---
- name: Install orthanc
  hosts: myhosts
  tasks:
    - name: Install orthanc
      ansible.builtin.package:
        name: orthanc
    - name: Change orthanc default password
      ansible.builtin.package:
        name: orthanc
